_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -88.1982
  - 30.6568
  - 5
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 0
name: Basic Map
source: "mapbox:///mapbox.mapbox-streets-v7"
styles: 
  - style.mss
  - roads.mss
template: ''
